# SPDX-License-Identifier: GPL-2.0
#
# Intel SGX
#

obj-$(CONFIG_INTEL_SGX) += intel_sgx.o

intel_sgx-$(CONFIG_INTEL_SGX) += \
	sgx_ioctl.o \
	sgx_encl.o \
	sgx_encl_page.o \
	sgx_main.o \
	sgx_fault.o \
	sgx_vma.o \
